
  const MENU = [
    { comidas: [
      {nombre: "Arrozconleche",
      descripcion: "arroz con leche",
      numeroRaciones: 500,
      comidaTipo: "DESAYUNO",
      dia:"2018-04-02",
      inicioReserva: "06:00:00",
      finReserva: "07:00:00"},
      {nombre: "arrozconpollo",
       descripcion: "arroz con pollo",
      numeroRaciones: 50,
      comidaTipo: "ALMUERZO",
      dia:"2018-04-02",
      inicioReserva: "07:00:00",
      finReserva: "12:00:00"},
      {nombre: "arroz con pure",
      descripcion: "arroz con pollo",
      numeroRaciones: 50,
      comidaTipo: "CENA",
      dia:"2018-04-02",
      inicioReserva: "02:00:00",
      finReserva: "05:00:00"},
    ],
     dia: 'LUNES' },
     { comidas: [
      {nombre: "Pan con queso",
      descripcion: "Pan con queso",
      numeroRaciones: 500,
      comidaTipo: "DESAYUNO",
      dia:"2018-04-03",
      inicioReserva: '06:00:00',
      finReserva: '07:00:00'},
      {nombre: "arrozconpollo",
       descripcion: "arroz con pollo",
      numeroRaciones: 500,
      comidaTipo: "ALMUERZO",
      dia:"2018-04-03",
      inicioReserva: '07:00:00',
      finReserva: '12:00:00'},
      {nombre: "arrozconpollo",
      descripcion: "arroz con pollo",
      numeroRaciones: 500,
      comidaTipo: "CENA",
      dia:"2018-04-03",
      inicioReserva: '02:00:00',
      finReserva: '05:00:00'},
    ],
     dia: 'MARTES' },
     { comidas: [
      {nombre: "Pan con hotdog",
      descripcion: "Pan con hotdog",
      numeroRaciones: 500,
      comidaTipo: "DESAYUNO",
      dia:"2018-04-04",
      inicioReserva: '06:00:00',
      finReserva: '07:00:00'},
      {nombre: "arrozconpollo",
       descripcion: "arroz con pollo",
      numeroRaciones: 500,
      comidaTipo: "ALMUERZO",
      dia:"2018-04-04",
      inicioReserva: '07:00:00',
      finReserva: '12:00:00'},
      {nombre: "arroz con pure",
      descripcion: "arroz con pollo",
      numeroRaciones: 500,
      comidaTipo: "CENA",
      dia:"2018-04-04",
      inicioReserva: '02:00:00',
      finReserva: '05:00:00'},
    ],
     dia: 'MIERCOLES' },
     { comidas: [
      {nombre: "Pan con palta",
      descripcion: "Pan con palta",
      numeroRaciones: 500,
      comidaTipo: "DESAYUNO",
      dia:"2018-04-05",
      inicioReserva: '06:00:00',
      finReserva: '07:00:00'},
      {nombre: "arrozconpollo",
       descripcion: "arroz con pollo",
      numeroRaciones: 500,
      comidaTipo: "ALMUERZO",
      dia:"2018-04-05",
      inicioReserva: '07:00:00',
      finReserva: '12:00:00'},
      {nombre: "arroz con pure",
      descripcion: "arroz con pollo",
      numeroRaciones: 500,
      comidaTipo: "CENA",
      dia:"2018-04-05",
      inicioReserva: '02:00:00',
      finReserva: '05:00:00'},
    ],
     dia: 'JUEVES' },
     { comidas: [
      {nombre: "Pan con pollo",
      descripcion: "Pan con pollo",
      numeroRaciones: 500,
      comidaTipo: "DESAYUNO",
      dia:"2018-04-06",
      inicioReserva: '06:00:00',
      finReserva: '07:00:00'},
      {nombre: "arrozconpollo",
       descripcion: "arroz con pollo",
      numeroRaciones: 500,
      comidaTipo: "ALMUERZO",
      dia:"2018-04-06",
      inicioReserva: '07:00:00',
      finReserva: '12:00:00'},
      {nombre: "arroz con pure",
      descripcion: "arroz con pollo",
      numeroRaciones: 500,
      comidaTipo: "CENA",
      dia:"2018-04-06",
      inicioReserva: '02:00:00',
      finReserva: '05:00:00'},
    ],
     dia: 'VIERNES' },
     { comidas: [
      {nombre: "Pan con pollo",
      descripcion: "Pan con pollo",
      numeroRaciones: 500,
      comidaTipo: "DESAYUNO",
      dia:"2018-04-07",
      inicioReserva: '06:00:00',
      finReserva: '07:00:00'},
      {nombre: "arrozconpollo",
       descripcion: "arroz con pollo",
      numeroRaciones: 500,
      comidaTipo: "ALMUERZO",
      dia:"2018-04-07",
      inicioReserva: '07:00:00',
      finReserva: '12:00:00'},
      {nombre: "arroz con pure",
      descripcion: "arroz con pollo",
      numeroRaciones: 500,
      comidaTipo: "CENA",
      dia:"2018-04-07",
      inicioReserva: '02:00:00',
      finReserva: '05:00:00'},
    ],
     dia: 'SABADO' },
     { comidas: [
      {nombre: "Pan con hotdog",
      descripcion: "Pan con hotdog",
      numeroRaciones: 500,
      comidaTipo: "DESAYUNO",
      dia:"2018-04-08",
      inicioReserva: '6:00:00',
      finReserva: '7:00:00'},
      {nombre: "arrozconpollo",
       descripcion: "arroz con pollo",
      numeroRaciones: 500,
      comidaTipo: "ALMUERZO",
      dia:"2018-04-08",
      inicioReserva: '07:00:00',
      finReserva: '12:00:00'},
      {nombre: "arroz con pure",
      descripcion: "arroz con pollo",
      numeroRaciones: 500,
      comidaTipo: "CENA",
      dia:"2018-04-08",
      inicioReserva: '02:00:00',
      finReserva: '05:00:00'},
    ],
     dia: 'DOMINGO' },
     
  ];

  export default MENU;