
  const MENU = [
    { comidas: [
      {nombre: "Arrozconleche",
      descripcion: "arroz con leche",
      numeroRaciones: 50,
      comidaTipo: "DESAYUNO",
      dia:"",
      inicioReserva: "5",
      finReserva: "5"},
      {nombre: "arrozconpollo",
       descripcion: "arroz con pollo",
      numeroRaciones: 50,
      comidaTipo: "ALMUERZO",
      dia:"",
      inicioReserva: "5",
      finReserva: "5"},
      {nombre: "arroz con pure",
      descripcion: "arroz con pollo",
      numeroRaciones: 5,
      comidaTipo: "CENA",
      dia:"",
      inicioReserva: "5",
      finReserva: "5"},
    ],
     dia: 'LUNES' },
     { comidas: [
      {nombre: "Pan con queso",
      descripcion: "Pan con queso",
      numeroRaciones: 50,
      comidaTipo: "DESAYUNO",
      dia:"",
      inicioReserva: "5",
      finReserva: "5"},
      {nombre: "arrozconpollo",
       descripcion: "arroz con pollo",
      numeroRaciones: 50,
      comidaTipo: "ALMUERZO",
      dia:"",
      inicioReserva: "5",
      finReserva: "5"},
      {nombre: "arrozconpollo",
      descripcion: "arroz con pollo",
      numeroRaciones: 50,
      comidaTipo: "CENA",
      dia:"",
      inicioReserva: "5",
      finReserva: "5"},
    ],
     dia: 'MARTES' },
     { comidas: [
      {nombre: "Pan con hotdog",
      descripcion: "Pan con hotdog",
      numeroRaciones: 50,
      comidaTipo: "DESAYUNO",
      dia:"",
      inicioReserva: "5",
      finReserva: "5"},
      {nombre: "arrozconpollo",
       descripcion: "arroz con pollo",
      numeroRaciones: 50,
      comidaTipo: "ALMUERZO",
      dia:"",
      inicioReserva: "5",
      finReserva: "5"},
      {nombre: "arroz con pure",
      descripcion: "arroz con pollo",
      numeroRaciones: 5,
      comidaTipo: "CENA",
      dia:"",
      inicioReserva: "5",
      finReserva: "5"},
    ],
     dia: 'MIERCOLES' },
     { comidas: [
      {nombre: "Pan con palta",
      descripcion: "Pan con palta",
      numeroRaciones: 50,
      comidaTipo: "DESAYUNO",
      dia:"",
      inicioReserva: "5",
      finReserva: "5"},
      {nombre: "arrozconpollo",
       descripcion: "arroz con pollo",
      numeroRaciones: 50,
      comidaTipo: "ALMUERZO",
      dia:"",
      inicioReserva: "5",
      finReserva: "5"},
      {nombre: "arroz con pure",
      descripcion: "arroz con pollo",
      numeroRaciones: 5,
      comidaTipo: "CENA",
      dia:"",
      inicioReserva: "5",
      finReserva: "5"},
    ],
     dia: 'JUEVES' },
     { comidas: [
      {nombre: "Pan con pollo",
      descripcion: "Pan con pollo",
      numeroRaciones: 50,
      comidaTipo: "DESAYUNO",
      dia:"",
      inicioReserva: "5",
      finReserva: "5"},
      {nombre: "arrozconpollo",
       descripcion: "arroz con pollo",
      numeroRaciones: 50,
      comidaTipo: "ALMUERZO",
      dia:"",
      inicioReserva: "5",
      finReserva: "5"},
      {nombre: "arroz con pure",
      descripcion: "arroz con pollo",
      numeroRaciones: 5,
      comidaTipo: "CENA",
      dia:"",
      inicioReserva: "5",
      finReserva: "5"},
    ],
     dia: 'VIERNES' },
     { comidas: [
      {nombre: "Pan con pollo",
      descripcion: "Pan con pollo",
      numeroRaciones: 50,
      comidaTipo: "DESAYUNO",
      dia:"",
      inicioReserva: "5",
      finReserva: "5"},
      {nombre: "arrozconpollo",
       descripcion: "arroz con pollo",
      numeroRaciones: 50,
      comidaTipo: "ALMUERZO",
      dia:"",
      inicioReserva: "5",
      finReserva: "5"},
      {nombre: "arroz con pure",
      descripcion: "arroz con pollo",
      numeroRaciones: 5,
      comidaTipo: "CENA",
      dia:"",
      inicioReserva: "5",
      finReserva: "5"},
    ],
     dia: 'SABADO' },
     { comidas: [
      {nombre: "Pan con hotdog",
      descripcion: "Pan con hotdog",
      numeroRaciones: 50,
      comidaTipo: "DESAYUNO",
      dia:"",
      inicioReserva: "5",
      finReserva: "5"},
      {nombre: "arrozconpollo",
       descripcion: "arroz con pollo",
      numeroRaciones: 50,
      comidaTipo: "ALMUERZO",
      dia:"",
      inicioReserva: "5",
      finReserva: "5"},
      {nombre: "arroz con pure",
      descripcion: "arroz con pollo",
      numeroRaciones: 5,
      comidaTipo: "CENA",
      dia:"",
      inicioReserva: "5",
      finReserva: "5"},
    ],
     dia: 'DOMINGO' },
     
  ];

  export default MENU;